# Form implementation generated from reading ui file 'd:\My Projects\Python\Browser\UI_main.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 650)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_title = QtWidgets.QFrame(self.frame)
        self.frame_title.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_title.setStyleSheet("QFrame#frame_title{background-color:rgb(25, 35, 35);border-top-left-radius:7px;border-top-right-radius:7px;}\n"
"QFrame#label_title{color: rgb(0, 170, 255);padding-right: 100px;}\n"
"QPushButton#btn_close{\n"
"    background:transparent;\n"
"    color: rgba(207, 0, 15, 1);    \n"
"    margin:3px ;\n"
"    border-radius: 9px;\n"
"}\n"
"\n"
"QPushButton#btn_close:hover{\n"
"    color:rgb(255,255,255);\n"
"    background-color:  rgba(217, 30, 24, 1);\n"
"}\n"
"\n"
"QPushButton#btn_close:pressed{\n"
"    font-size: 11pt;\n"
"}\n"
"\n"
"QPushButton#btn_min{\n"
"    background:transparent;\n"
"    color:rgba(247, 202, 24, 1);\n"
"    margin:2px ;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton#btn_min:hover{\n"
"    color: rgb(5,5,5);\n"
"    background-color:rgba(245, 229, 27, 1);\n"
"}\n"
"\n"
"QPushButton#btn_min:pressed{\n"
"\n"
"    font-size: 11pt;\n"
"}\n"
"\n"
"QPushButton#btn_max{\n"
"    background:transparent;\n"
"    color: rgba(68, 189, 50,1.0);\n"
"    margin:2px ;\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton#btn_max:hover{\n"
"    color: rgb(5,5,5);\n"
"    background-color: rgba(76, 209, 55,1.0);\n"
"}\n"
"\n"
"\n"
"")
        self.frame_title.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_title.setObjectName("frame_title")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_title)
        self.horizontalLayout_2.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_title = QtWidgets.QLabel(self.frame_title)
        self.label_title.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_2.addWidget(self.label_title, 0, QtCore.Qt.AlignLeft)
        self.btn_min = QtWidgets.QPushButton(self.frame_title)
        self.btn_min.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_min.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("dripicons-v2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_min.setFont(font)
        self.btn_min.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_min.setObjectName("btn_min")
        self.horizontalLayout_2.addWidget(self.btn_min)
        self.btn_max = QtWidgets.QPushButton(self.frame_title)
        self.btn_max.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_max.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("dripicons-v2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.btn_max.setFont(font)
        self.btn_max.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_max.setObjectName("btn_max")
        self.horizontalLayout_2.addWidget(self.btn_max)
        self.btn_close = QtWidgets.QPushButton(self.frame_title)
        self.btn_close.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_close.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("dripicons-v2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_close.setFont(font)
        self.btn_close.setToolTip("")
        self.btn_close.setStatusTip("")
        self.btn_close.setWhatsThis("")
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_2.addWidget(self.btn_close)
        self.verticalLayout_2.addWidget(self.frame_title)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_link = QtWidgets.QFrame(self.frame_3)
        self.frame_link.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_link.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_link.setStyleSheet("QFrame#frame_link{background-color:rgb(25, 35, 35);border-top: 1px solid  rgb(217, 0, 0);}\n"
"\n"
"QPushButton{color: rgba(210, 215, 211, 1);    background:transparent;border-radius:10px;margin:2px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgba(228, 233, 237, 1);\n"
"    background-color:rgba(189, 195, 199, 0.3);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: rgba(242, 241, 239, 1);\n"
"    background-color: rgba(171, 183, 183, 0.5);\n"
"    padding-top: 1px;\n"
"    background-position: calc(100% - 10px)center;\n"
"}\n"
"\n"
"QLineEdit{border-radius: 6px;padding-left: 5px;margin-right: 3px;}")
        self.frame_link.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_link.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_link.setObjectName("frame_link")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_link)
        self.horizontalLayout.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_back = QtWidgets.QPushButton(self.frame_link)
        self.btn_back.setMinimumSize(QtCore.QSize(25, 25))
        self.btn_back.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("dripicons-v2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_back.setFont(font)
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout.addWidget(self.btn_back)
        self.btn_forward = QtWidgets.QPushButton(self.frame_link)
        self.btn_forward.setMinimumSize(QtCore.QSize(25, 25))
        self.btn_forward.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("dripicons-v2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_forward.setFont(font)
        self.btn_forward.setObjectName("btn_forward")
        self.horizontalLayout.addWidget(self.btn_forward)
        self.btn_reload = QtWidgets.QPushButton(self.frame_link)
        self.btn_reload.setMinimumSize(QtCore.QSize(25, 25))
        self.btn_reload.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("dripicons-v2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_reload.setFont(font)
        self.btn_reload.setObjectName("btn_reload")
        self.horizontalLayout.addWidget(self.btn_reload)
        self.lineEdit_url = QtWidgets.QLineEdit(self.frame_link)
        self.lineEdit_url.setMinimumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setItalic(False)
        self.lineEdit_url.setFont(font)
        self.lineEdit_url.setText("")
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.horizontalLayout.addWidget(self.lineEdit_url)
        self.verticalLayout_3.addWidget(self.frame_link)
        self.frame_body = QtWidgets.QFrame(self.frame_3)
        self.frame_body.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.frame_body.setToolTip("")
        self.frame_body.setStyleSheet("background-color:rgba(46, 49, 49, 1);")
        self.frame_body.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_body.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_body.setObjectName("frame_body")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_body)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.frame_body)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout_3.addWidget(self.frame_body)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "A.I.T  BROWSER V.1.0"))
        self.btn_min.setText(_translate("MainWindow", ""))
        self.btn_max.setText(_translate("MainWindow", ""))
        self.btn_close.setText(_translate("MainWindow", "9"))
        self.btn_back.setText(_translate("MainWindow", "l"))
        self.btn_forward.setText(_translate("MainWindow", "m"))
        self.btn_reload.setText(_translate("MainWindow", "Z"))
        self.lineEdit_url.setPlaceholderText(_translate("MainWindow", "https:// www.google.com"))
